- id: check-build-assets
  name: ensure assets are bundled
  description: Make sure that `npm run build` was ran before commiting.
  language: script
  types_or: [css, javascript, svg]
  entry: check-build-assets.sh
