version: 2.1

orbs:
  browser-tools: circleci/browser-tools@1.4.7

commands:
  run-tests:
    description: "Run test suite"
    steps:
      - browser-tools/install-chrome
      - browser-tools/install-chromedriver
      - checkout
      - run: npm ci
      - run: npm run test
  run-checks:
    description: "Run basic checks"
    steps:
      - checkout
      - run: npm ci
      - run: npm run lint
  run-build:
    description: "Ensure compiled assets are up to date and HTML is valid"
    steps:
      - checkout
      - run: npm ci
      - run: npm run build

jobs:
  checks:
    docker:
      - image: "cimg/node:22.14.0"
    steps:
      - run-checks: {}
  test:
    docker:
      - image: "cimg/node:22.14.0-browsers"
    steps:
      - run-tests: {}
  build:
    docker:
      - image: "cimg/node:22.14.0"
    steps:
      - run-build: {}

workflows:
  version: 2
  build:
    jobs:
      - checks
      - build
      - test
